export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";

export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
